apiVersion: v1
kind: Secret
metadata:
  name: nexusops-secrets
  namespace: nexusops
type: Opaque
stringData:
  POSTGRES_PASSWORD: "nexus_secret_123"
  ConnectionStrings__DefaultConnection: "Host=postgres;Database=nexusops_db;Username=nexus_admin;Password=nexus_secret_123"
  RABBITMQ_DEFAULT_PASS: "nexus_secret_123"
