apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.database.postgres.password | quote }}
  ConnectionStrings__DefaultConnection: {{ printf "Host=%s-postgres;Database=%s;Username=%s;Password=%s" .Release.Name .Values.database.postgres.dbName .Values.database.postgres.username .Values.database.postgres.password | quote }}
  RABBITMQ_DEFAULT_PASS: {{ .Values.messaging.rabbitmq.password | quote }}
