global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'dotnet_api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['backend-dotnet:5000']

  - job_name: 'fastapi_ai'
    metrics_path: '/api/v1/metrics'
    static_configs:
      - targets: ['backend-ai-fastapi:8000']
